[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = ".vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && pnpm run build"

[[redirects]]
  from = "https://cn-vitest.netlify.app/*"
  to = "https://cn.vitest.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
